### PR TITLE
Update prettier config and docs typos

### PR DESCRIPTION
**Pull request by tonytkachenko**

### CODE REVIEW

**Review by KnorpelSenf — CHANGES_REQUESTED** [review]
I think it makes the more sense to completely get rid of Node tooling here, and align this repo with the core repo. There, we use Deno tooling for everything. That way, we get the best consistency.

Can you perform these changes?

This plugin was simply one of the first plugins that got published, so the choices back then were a bit different. Thanks for keeping this up to date!

**Comment by tonytkachenko** [comment]
Okay, I'll do that one of these days

**Comment by KnorpelSenf** [comment]
@tonytkachenko are you still working on this?

**Comment by KnorpelSenf** [comment]
Closing because of inactivity. Please comment or reopen if you want to pick this up.

**Pull request closed without merging**
